name: flutter_advanced
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1000002

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  状态管理
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^3.2.0
  dio: ^4.0.0
  # 下拉刷新插件
  flutter_easyrefresh: ^2.2.0
  # 视频播放器
  video_player: ^2.1.1
  # 跑马灯
  marquee: ^2.1.0
  # 懒加载的层叠组件
  proste_indexed_stack: ^0.1.1
  # 底部扩散模糊动画
  ripple_backdrop_animate_route: ^0.2.0
  # json转model
  json_annotation: ^4.1.0
  json_serializable: 6.6.1
  build_runner: 2.3.3
  # 通信
  web_socket_channel: ^2.0.0
  shared_preferences: ^2.0.7
  path_provider: ^2.0.1
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  fluttertoast: ^8.0.9
  pdf_render: ^1.0.23
  sp_util: ^2.0.3
  flustars: ^2.0.1
  floor: 1.1.0
  cached_network_image: ^3.1.0
  #http缓存
#  dio_http_cache: 0.3.0
  hb_check_code: ^0.0.1
  flutter_easyloading: ^3.0.0
  permission_handler: 8.3.0
  draggable_widget: ^2.0.0
  flutter_cube: ^0.1.1
  signature: ^5.3.2
  appbar_animated: ^0.0.3
  flutter_picker:
    git: http://github.com/yangyxd/flutter_picker.git



dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
